//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ets.OAuthServer.Bll.EtsSmsService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendType", Namespace="http://tempuri.org/")]
    public enum SmsSendType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        亿美软通 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        营销渠道 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        天润融通 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        百分通联 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        云信 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        梦网 = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EtsSmsService.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: Generating message contract since element name Mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse SendSms(Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse> SendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name Mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsResult", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse SendSmsResult(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsResult", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse> SendSmsResultAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLog", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse SendSmsSaveLog(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse> SendSmsSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNoSign", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse SendSmsSaveLogNoSign(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNoSign", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse> SendSmsSaveLogNoSignAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNew", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse SendSmsSaveLogNew(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNew", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse> SendSmsSaveLogNewAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogB2B", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse SendSmsSaveLogB2B(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogB2B", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse> SendSmsSaveLogB2BAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest request);
        
        // CODEGEN: Generating message contract since element name GetSendedSmsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendedSms", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse GetSendedSms(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendedSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse> GetSendedSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceSendSms", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse VoiceSendSms(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceSendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse> VoiceSendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBaseSaveLog", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse SendSmsBaseSaveLog(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBaseSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse> SendSmsBaseSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest request);
        
        // CODEGEN: Generating message contract since element name Mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse SendSmsBase(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse> SendSmsBaseAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSmsSaveLog", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse MsgSendSmsSaveLog(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSmsSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse> MsgSendSmsSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse MsgSendSms(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse> MsgSendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpeedSend", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse SpeedSend(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpeedSend", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse> SpeedSendAsync(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest request);
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBlance", ReplyAction="*")]
        Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse GetAllBlance(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBlance", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse> GetAllBlanceAsync(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResult", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequestBody Body;
        
        public SendSmsResultRequest() {
        }
        
        public SendSmsResultRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsResultRequestBody() {
        }
        
        public SendSmsResultRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponseBody Body;
        
        public SendSmsResultResponse() {
        }
        
        public SendSmsResultResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResultResult;
        
        public SendSmsResultResponseBody() {
        }
        
        public SendSmsResultResponseBody(string SendSmsResultResult) {
            this.SendSmsResultResult = SendSmsResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequestBody Body;
        
        public SendSmsSaveLogRequest() {
        }
        
        public SendSmsSaveLogRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        public SendSmsSaveLogRequestBody() {
        }
        
        public SendSmsSaveLogRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponseBody Body;
        
        public SendSmsSaveLogResponse() {
        }
        
        public SendSmsSaveLogResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogResult;
        
        public SendSmsSaveLogResponseBody() {
        }
        
        public SendSmsSaveLogResponseBody(string SendSmsSaveLogResult) {
            this.SendSmsSaveLogResult = SendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNoSignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNoSign", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequestBody Body;
        
        public SendSmsSaveLogNoSignRequest() {
        }
        
        public SendSmsSaveLogNoSignRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNoSignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        public SendSmsSaveLogNoSignRequestBody() {
        }
        
        public SendSmsSaveLogNoSignRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNoSignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNoSignResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponseBody Body;
        
        public SendSmsSaveLogNoSignResponse() {
        }
        
        public SendSmsSaveLogNoSignResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNoSignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogNoSignResult;
        
        public SendSmsSaveLogNoSignResponseBody() {
        }
        
        public SendSmsSaveLogNoSignResponseBody(string SendSmsSaveLogNoSignResult) {
            this.SendSmsSaveLogNoSignResult = SendSmsSaveLogNoSignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNew", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequestBody Body;
        
        public SendSmsSaveLogNewRequest() {
        }
        
        public SendSmsSaveLogNewRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int groupId;
        
        public SendSmsSaveLogNewRequestBody() {
        }
        
        public SendSmsSaveLogNewRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, int groupId) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponseBody Body;
        
        public SendSmsSaveLogNewResponse() {
        }
        
        public SendSmsSaveLogNewResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogNewResult;
        
        public SendSmsSaveLogNewResponseBody() {
        }
        
        public SendSmsSaveLogNewResponseBody(string SendSmsSaveLogNewResult) {
            this.SendSmsSaveLogNewResult = SendSmsSaveLogNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogB2BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogB2B", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequestBody Body;
        
        public SendSmsSaveLogB2BRequest() {
        }
        
        public SendSmsSaveLogB2BRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogB2BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int groupId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsPlatform;
        
        public SendSmsSaveLogB2BRequestBody() {
        }
        
        public SendSmsSaveLogB2BRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, int groupId, string smsPlatform) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.groupId = groupId;
            this.smsPlatform = smsPlatform;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogB2BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogB2BResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponseBody Body;
        
        public SendSmsSaveLogB2BResponse() {
        }
        
        public SendSmsSaveLogB2BResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogB2BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogB2BResult;
        
        public SendSmsSaveLogB2BResponseBody() {
        }
        
        public SendSmsSaveLogB2BResponseBody(string SendSmsSaveLogB2BResult) {
            this.SendSmsSaveLogB2BResult = SendSmsSaveLogB2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSendedSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSendedSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequestBody Body;
        
        public GetSendedSmsRequest() {
        }
        
        public GetSendedSmsRequest(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSendedSmsRequestBody {
        
        public GetSendedSmsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSendedSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSendedSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponseBody Body;
        
        public GetSendedSmsResponse() {
        }
        
        public GetSendedSmsResponse(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSendedSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSendedSmsResult;
        
        public GetSendedSmsResponseBody() {
        }
        
        public GetSendedSmsResponseBody(string GetSendedSmsResult) {
            this.GetSendedSmsResult = GetSendedSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequestBody Body;
        
        public VoiceSendSmsRequest() {
        }
        
        public VoiceSendSmsRequest(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        public VoiceSendSmsRequestBody() {
        }
        
        public VoiceSendSmsRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponseBody Body;
        
        public VoiceSendSmsResponse() {
        }
        
        public VoiceSendSmsResponse(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VoiceSendSmsResult;
        
        public VoiceSendSmsResponseBody() {
        }
        
        public VoiceSendSmsResponseBody(string VoiceSendSmsResult) {
            this.VoiceSendSmsResult = VoiceSendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequestBody Body;
        
        public SendSmsBaseSaveLogRequest() {
        }
        
        public SendSmsBaseSaveLogRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public SendSmsBaseSaveLogRequestBody() {
        }
        
        public SendSmsBaseSaveLogRequestBody(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponseBody Body;
        
        public SendSmsBaseSaveLogResponse() {
        }
        
        public SendSmsBaseSaveLogResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseSaveLogResult;
        
        public SendSmsBaseSaveLogResponseBody() {
        }
        
        public SendSmsBaseSaveLogResponseBody(string SendSmsBaseSaveLogResult) {
            this.SendSmsBaseSaveLogResult = SendSmsBaseSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBase", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequestBody Body;
        
        public SendSmsBaseRequest() {
        }
        
        public SendSmsBaseRequest(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type;
        
        public SendSmsBaseRequestBody() {
        }
        
        public SendSmsBaseRequestBody(string Mobile, string Content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type) {
            this.Mobile = Mobile;
            this.Content = Content;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponseBody Body;
        
        public SendSmsBaseResponse() {
        }
        
        public SendSmsBaseResponse(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseResult;
        
        public SendSmsBaseResponseBody() {
        }
        
        public SendSmsBaseResponseBody(string SendSmsBaseResult) {
            this.SendSmsBaseResult = SendSmsBaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequestBody Body;
        
        public MsgSendSmsSaveLogRequest() {
        }
        
        public MsgSendSmsSaveLogRequest(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public MsgSendSmsSaveLogRequestBody() {
        }
        
        public MsgSendSmsSaveLogRequestBody(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponseBody Body;
        
        public MsgSendSmsSaveLogResponse() {
        }
        
        public MsgSendSmsSaveLogResponse(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsSaveLogResult;
        
        public MsgSendSmsSaveLogResponseBody() {
        }
        
        public MsgSendSmsSaveLogResponseBody(string MsgSendSmsSaveLogResult) {
            this.MsgSendSmsSaveLogResult = MsgSendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequestBody Body;
        
        public MsgSendSmsRequest() {
        }
        
        public MsgSendSmsRequest(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public MsgSendSmsRequestBody() {
        }
        
        public MsgSendSmsRequestBody(string mobile, string content) {
            this.mobile = mobile;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponseBody Body;
        
        public MsgSendSmsResponse() {
        }
        
        public MsgSendSmsResponse(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsResult;
        
        public MsgSendSmsResponseBody() {
        }
        
        public MsgSendSmsResponseBody(string MsgSendSmsResult) {
            this.MsgSendSmsResult = MsgSendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SpeedSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SpeedSend", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequestBody Body;
        
        public SpeedSendRequest() {
        }
        
        public SpeedSendRequest(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SpeedSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string groupIdOrsign;
        
        public SpeedSendRequestBody() {
        }
        
        public SpeedSendRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, string groupIdOrsign) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.groupIdOrsign = groupIdOrsign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SpeedSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SpeedSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponseBody Body;
        
        public SpeedSendResponse() {
        }
        
        public SpeedSendResponse(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SpeedSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SpeedSendResult;
        
        public SpeedSendResponseBody() {
        }
        
        public SpeedSendResponseBody(string SpeedSendResult) {
            this.SpeedSendResult = SpeedSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBlanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBlance", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequestBody Body;
        
        public GetAllBlanceRequest() {
        }
        
        public GetAllBlanceRequest(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBlanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetAllBlanceRequestBody() {
        }
        
        public GetAllBlanceRequestBody(string account, string pwd) {
            this.account = account;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBlanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBlanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponseBody Body;
        
        public GetAllBlanceResponse() {
        }
        
        public GetAllBlanceResponse(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBlanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllBlanceResult;
        
        public GetAllBlanceResponseBody() {
        }
        
        public GetAllBlanceResponseBody(string GetAllBlanceResult) {
            this.GetAllBlanceResult = GetAllBlanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : Ets.OAuthServer.Bll.EtsSmsService.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<Ets.OAuthServer.Bll.EtsSmsService.SmsSoap>, Ets.OAuthServer.Bll.EtsSmsService.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSms(Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string Mobile, string Content) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResponse> SendSmsAsync(string Mobile, string Content) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsResult(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest request) {
            return base.Channel.SendSmsResult(request);
        }
        
        public string SendSmsResult(string Mobile, string Content) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsResult(inValue);
            return retVal.Body.SendSmsResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsResultAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest request) {
            return base.Channel.SendSmsResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultResponse> SendSmsResultAsync(string Mobile, string Content) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsResultRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLog(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest request) {
            return base.Channel.SendSmsSaveLog(request);
        }
        
        public string SendSmsSaveLog(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLog(inValue);
            return retVal.Body.SendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest request) {
            return base.Channel.SendSmsSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogResponse> SendSmsSaveLogAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogNoSign(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest request) {
            return base.Channel.SendSmsSaveLogNoSign(request);
        }
        
        public string SendSmsSaveLogNoSign(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogNoSign(inValue);
            return retVal.Body.SendSmsSaveLogNoSignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogNoSignAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest request) {
            return base.Channel.SendSmsSaveLogNoSignAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignResponse> SendSmsSaveLogNoSignAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNoSignRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogNoSignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogNew(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest request) {
            return base.Channel.SendSmsSaveLogNew(request);
        }
        
        public string SendSmsSaveLogNew(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, int groupId) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            inValue.Body.groupId = groupId;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogNew(inValue);
            return retVal.Body.SendSmsSaveLogNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogNewAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest request) {
            return base.Channel.SendSmsSaveLogNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewResponse> SendSmsSaveLogNewAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, int groupId) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogNewRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            inValue.Body.groupId = groupId;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogB2B(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest request) {
            return base.Channel.SendSmsSaveLogB2B(request);
        }
        
        public string SendSmsSaveLogB2B(string mobile, string content, string smsSource, System.Nullable<int> supplierID, int groupId, string smsPlatform) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.groupId = groupId;
            inValue.Body.smsPlatform = smsPlatform;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogB2B(inValue);
            return retVal.Body.SendSmsSaveLogB2BResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsSaveLogB2BAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest request) {
            return base.Channel.SendSmsSaveLogB2BAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BResponse> SendSmsSaveLogB2BAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, int groupId, string smsPlatform) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsSaveLogB2BRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.groupId = groupId;
            inValue.Body.smsPlatform = smsPlatform;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsSaveLogB2BAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.GetSendedSms(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest request) {
            return base.Channel.GetSendedSms(request);
        }
        
        public string GetSendedSms() {
            Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequestBody();
            Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).GetSendedSms(inValue);
            return retVal.Body.GetSendedSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.GetSendedSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest request) {
            return base.Channel.GetSendedSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsResponse> GetSendedSmsAsync() {
            Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.GetSendedSmsRequestBody();
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).GetSendedSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.VoiceSendSms(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest request) {
            return base.Channel.VoiceSendSms(request);
        }
        
        public string VoiceSendSms(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).VoiceSendSms(inValue);
            return retVal.Body.VoiceSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.VoiceSendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest request) {
            return base.Channel.VoiceSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsResponse> VoiceSendSmsAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.VoiceSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).VoiceSendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsBaseSaveLog(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest request) {
            return base.Channel.SendSmsBaseSaveLog(request);
        }
        
        public string SendSmsBaseSaveLog(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsBaseSaveLog(inValue);
            return retVal.Body.SendSmsBaseSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsBaseSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest request) {
            return base.Channel.SendSmsBaseSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogResponse> SendSmsBaseSaveLogAsync(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsBaseSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsBase(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBase(request);
        }
        
        public string SendSmsBase(string Mobile, string Content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsBase(inValue);
            return retVal.Body.SendSmsBaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SendSmsBaseAsync(Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseResponse> SendSmsBaseAsync(string Mobile, string Content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type) {
            Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SendSmsBaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.MsgSendSmsSaveLog(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest request) {
            return base.Channel.MsgSendSmsSaveLog(request);
        }
        
        public string MsgSendSmsSaveLog(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).MsgSendSmsSaveLog(inValue);
            return retVal.Body.MsgSendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.MsgSendSmsSaveLogAsync(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest request) {
            return base.Channel.MsgSendSmsSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogResponse> MsgSendSmsSaveLogAsync(string mobile, string content, Ets.OAuthServer.Bll.EtsSmsService.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).MsgSendSmsSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.MsgSendSms(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSms(request);
        }
        
        public string MsgSendSms(string mobile, string content) {
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).MsgSendSms(inValue);
            return retVal.Body.MsgSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.MsgSendSmsAsync(Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsResponse> MsgSendSmsAsync(string mobile, string content) {
            Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).MsgSendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SpeedSend(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest request) {
            return base.Channel.SpeedSend(request);
        }
        
        public string SpeedSend(string mobile, string content, string smsSource, System.Nullable<int> supplierID, string groupIdOrsign) {
            Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.groupIdOrsign = groupIdOrsign;
            Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SpeedSend(inValue);
            return retVal.Body.SpeedSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.SpeedSendAsync(Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest request) {
            return base.Channel.SpeedSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.SpeedSendResponse> SpeedSendAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, string groupIdOrsign) {
            Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.SpeedSendRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.groupIdOrsign = groupIdOrsign;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).SpeedSendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.GetAllBlance(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest request) {
            return base.Channel.GetAllBlance(request);
        }
        
        public string GetAllBlance(string account, string pwd) {
            Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.pwd = pwd;
            Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse retVal = ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).GetAllBlance(inValue);
            return retVal.Body.GetAllBlanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse> Ets.OAuthServer.Bll.EtsSmsService.SmsSoap.GetAllBlanceAsync(Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest request) {
            return base.Channel.GetAllBlanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceResponse> GetAllBlanceAsync(string account, string pwd) {
            Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest inValue = new Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequest();
            inValue.Body = new Ets.OAuthServer.Bll.EtsSmsService.GetAllBlanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.pwd = pwd;
            return ((Ets.OAuthServer.Bll.EtsSmsService.SmsSoap)(this)).GetAllBlanceAsync(inValue);
        }
    }
}
