// <auto-generated />
namespace Ets.OAuthServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class OAuthServer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OAuthServer));
        
        string IMigrationMetadata.Id
        {
            get { return "201510280711070_OAuthServer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
